mutation sessionCreate($input: SessionCreateInput!) {
  sessionCreate(input: $input) {
    fullName
    token
  }
}

query customers {
  customers {
    createdAt
    email
    id
    name
    phone
  }
}

query customer($id: ID!) {
  customer(id: $id) {
    email
    id
    name
    phone
  }
}

mutation customerCreate($input: CustomerCreateInput!) {
  customerCreate(input: $input)
}

mutation customerUpdate($input: CustomerUpdateInput!) {
  customerUpdate(input: $input)
}

mutation customerDelete($input: CustomerDeleteInput!) {
  customerDelete(input: $input)
}

query orders($includeCustomer: Boolean!) {
  orders {
    address
    createdAt
    currency
    customer @include(if: $includeCustomer) {
      name
    }
    id
    shippingFee
    status
    subtotal
    tax
    total
  }
}

query order($id: ID!) {
  order(id: $id) {
    address
    currency
    customerId
    id
    shippingFee
    status
    subtotal
    tax
    total
  }
}

mutation orderCreate($input: OrderCreateInput!) {
  orderCreate(input: $input)
}

mutation orderUpdate($input: OrderUpdateInput!) {
  orderUpdate(input: $input)
}

mutation orderDelete($input: OrderDeleteInput!) {
  orderDelete(input: $input)
}

query ordersSummary(
  $createdAtGt: ISO8601DateTime
  $createdAtLt: ISO8601DateTime
) {
  ordersSummary {
    avgAmount(createdAtGt: $createdAtGt, createdAtLt: $createdAtLt)
    countByStatus(createdAtGt: $createdAtGt, createdAtLt: $createdAtLt) {
      name
      value
    }
    revenueByMonth(createdAtGt: $createdAtGt, createdAtLt: $createdAtLt) {
      name
      value
    }
    totalCount(createdAtGt: $createdAtGt, createdAtLt: $createdAtLt)
    totalPendingCount: totalCount(
      createdAtGt: $createdAtGt
      createdAtLt: $createdAtLt
      status: pending
    )
    totalRevenue(createdAtGt: $createdAtGt, createdAtLt: $createdAtLt)
  }
}
